@echo off
setlocal enabledelayedexpansion

:: ============================================================================
:: Auto-Rust Windows Setup Script
:: - Detects CPU threads and optimizes build configuration
:: - Installs Rust if not present
:: - Creates .env file with template settings
:: - Builds release version
:: ============================================================================

echo ========================================
echo Auto-Rust Windows Setup
echo ========================================
echo.

:: ----------------------------------------------------------------------------
:: Step 1: CPU Detection and Optimization
:: ----------------------------------------------------------------------------
echo [1/5] Detecting CPU threads...

:: Get number of logical processors
for /f "tokens=2" %%a in ('wmic cpu get NumberOfLogicalProcessors /value ^| find "NumberOfLogicalProcessors"') do (
    set /a THREADS=%%a
)

if not defined THREADS set THREADS=4

:: Calculate optimal jobs (threads - 1 for system stability)
set /a JOBS=THREADS-1
if !JOBS! lss 1 set JOBS=1

echo Detected CPU threads: %THREADS%
echo Setting build jobs to: %JOBS% (threads - 1)
echo.

:: Create .cargo directory
if not exist ".cargo" mkdir .cargo

:: Create or update .cargo/config.toml
echo [2/5] Configuring Cargo for optimal builds...

(
    echo # Cargo configuration for faster builds with automatic CPU detection
    echo # Generated by setup-windows.bat on %DATE% %TIME%
    echo.
    echo [build]
    echo jobs = %JOBS%
    echo.
    echo # Windows-specific: use lld linker for faster builds
    echo # Install LLVM: choco install llvm
    echo # Then uncomment:
    echo # [target.x86_64-pc-windows-msvc]
    echo # linker = "lld-link.exe"
    echo.
    echo # Optional: Enable sccache for build caching
    echo # rustc-wrapper = "sccache"
    echo.
    echo [profile.dev]
    echo debug = "line-tables-only"
    echo opt-level = 1
    echo codegen-units = 256
    echo incremental = true
    echo.
    echo [profile.dev.build-override]
    echo opt-level = 3
    echo codegen-units = 16
    echo.
    echo [profile.release]
    echo lto = "thin"
    echo codegen-units = 64
    echo debug = "line-tables-only"
    echo opt-level = 3
    echo.
    echo [profile.release.build-override]
    echo opt-level = 3
    echo codegen-units = 16
    echo.
    echo # Fast release profile (no LTO, faster builds)
    echo [profile.fast-release]
    echo inherits = "release"
    echo lto = "off"
    echo codegen-units = 128
    echo opt-level = 2
) > .cargo\config.toml

echo Created .cargo/config.toml with %JOBS% parallel jobs
echo.

:: Set environment variable for current session
set CARGO_BUILD_JOBS=%JOBS%
setx CARGO_BUILD_JOBS %JOBS% >nul 2>&1
echo Set CARGO_BUILD_JOBS=%JOBS% in user environment
echo.

:: ----------------------------------------------------------------------------
:: Step 2: Check Rust Installation
:: ----------------------------------------------------------------------------
echo [3/5] Checking Rust installation...

rustc --version >nul 2>&1
if errorlevel 1 (
    echo Rust not found. Installing via rustup...
    curl --proto "=https" --tlsv1.2 -sSf https://sh.rustup.rs | sh
    call "%USERPROFILE%\.cargo\env"
) else (
    rustc --version
    echo Rust is already installed
)
echo.

:: ----------------------------------------------------------------------------
:: Step 3: Create .env File
:: ----------------------------------------------------------------------------
echo [4/5] Creating .env file...

if exist ".env" (
    echo .env file already exists, skipping...
) else (
    (
        echo # Auto-Rust Environment Configuration
        echo # Generated by setup-windows.bat
        echo.
        echo # =============================================================================
        echo # LLM Configuration
        echo # =============================================================================
        echo # Provider: "ollama" or "openrouter"
        echo LLM_PROVIDER=ollama
        echo.
        echo # OpenRouter Settings (get key from https://openrouter.ai/keys)
        echo OPENROUTER_API_KEY=
        echo OPENROUTER_MODEL=anthropic/claude-3-haiku
        echo.
        echo # Ollama Settings (local)
        echo OLLAMA_URL=http://localhost:11434
        echo OLLAMA_MODEL=llama3.2:3b
        echo.
        echo # =============================================================================
        echo # Twitter Activity Settings
        echo # =============================================================================
        echo TWITTER_LLM_ENABLED=false
        echo TWITTER_LLM_PROVIDER=ollama
        echo TWITTER_LLM_MODEL=llama3.2:3b
        echo TWITTER_LLM_REPLY_PROBABILITY=0.05
        echo TWITTER_LLM_QUOTE_PROBABILITY=0.15
        echo.
        echo # Engagement Limits
        echo TWITTER_MAX_LIKES=5
        echo TWITTER_MAX_RETWEETS=3
        echo TWITTER_MAX_FOLLOWS=2
        echo TWITTER_MAX_REPLIES=3
        echo TWITTER_MAX_THREAD_DIVES=3
        echo TWITTER_MAX_TOTAL_ACTIONS=10
        echo.
        echo # =============================================================================
        echo # Browser Configuration
        echo # =============================================================================
        echo ROXYBROWSER_API_URL=http://127.0.0.1:50000/
        echo ROXYBROWSER_API_KEY=
        echo.
        echo CURSOR_OVERLAY_MS=50
        echo.
        echo # =============================================================================
        echo # Orchestrator Settings
        echo # =============================================================================
        echo MAX_GLOBAL_CONCURRENCY=20
        echo TASK_TIMEOUT_MS=600000
        echo MAX_RETRIES=2
    ) > .env
    echo Created .env file with template settings
)
echo.

:: ----------------------------------------------------------------------------
:: Step 4: Build Project
:: ----------------------------------------------------------------------------
echo [5/5] Building project...
echo.

:: Clean previous builds
call cargo clean

:: Build release version
call cargo build --profile release --all-features

if errorlevel 1 (
    echo.
    echo ========================================
    echo Build failed! Check errors above.
    echo ========================================
    exit /b 1
)

echo.
echo ========================================
echo Setup Complete!
echo ========================================
echo.
echo Configuration:
echo - CPU threads detected: %THREADS%
echo - Build jobs: %JOBS% (using %THREADS% - 1 for system stability)
echo - Build profile: release (optimized)
echo.
echo Next steps:
echo 1. Add your API keys to .env file
echo 2. Run: cargo run --profile release --all-features
echo.
echo On your other machines:
echo - 24-thread PC: Run this script (will auto-detect and use 23 jobs)
echo - 12-thread VPS: Run this script (will auto-detect and use 11 jobs)
echo.

:: Keep window open if run directly
pause
