#!/usr/bin/env pwsh
<#
.SYNOPSIS
    Lint spec packages according to project conventions.
.DESCRIPTION
    Validates spec structure, status consistency, and required files.
    Never modifies spec files.
.PARAMETER Directory
    A spec root, bucket, or package directory to lint. Defaults to docs/specs.
.EXAMPLE
    .\spec-lint.ps1
.EXAMPLE
    .\spec-lint.ps1 -Directory "docs/specs/_active"
#>
# System-owned spec workspace lint. Do not edit this file unless the task is explicitly about the spec system.
[CmdletBinding()]
param(
    [Parameter(Mandatory = $false)]
    [string]$Directory = "docs/specs"
)

$ErrorActionPreference = "Stop"
$Root = Split-Path -Parent $MyInvocation.MyCommand.Path
$RequiredFiles = @(
    "README.md",
    "spec.yaml",
    "baseline.md",
    "internal-api-outline.md",
    "plan.md",
    "validation-checklist.md",
    "ci-commands.md",
    "decisions.md",
    "quality-rules.md",
    "implementation-notes.md"
)

function Throw-SpecLintError([string]$message) {
    throw $message
}

function Assert-ReadOnlyScript {
    $scriptPath = $PSCommandPath
    if (-not $scriptPath) {
        return
    }

    $raw = Get-Content -LiteralPath $scriptPath -Raw
    $raw = [regex]::Replace($raw, '(?s)<#.*?#>', '')
    $raw = (($raw -split "`r?`n") | Where-Object { $_ -notmatch '^\s*#' }) -join "`n"
    $raw = [regex]::Replace($raw, '(?ms)^function\s+Assert-ReadOnlyScript\b.*?(?=^function\s+Resolve-TargetPath\b)', '')
    $raw = [regex]::Replace($raw, "'(?:''|[^'])*'", "''")
    $raw = [regex]::Replace($raw, '"(?:``.|[^"])*"', '""')

    $mutatingCmdlets = @(
        'Set-Content',
        'Add-Content',
        'Out-File',
        'Move-Item',
        'Rename-Item',
        'Remove-Item',
        'Copy-Item',
        'Clear-Content',
        'Set-Item',
        'New-Item'
    )

    foreach ($cmdlet in $mutatingCmdlets) {
        if ($raw -match ("(?i)\b" + [regex]::Escape($cmdlet) + "\b")) {
            Throw-SpecLintError "spec-lint.ps1 must stay read-only. Found mutating cmdlet: $cmdlet"
        }
    }
}

function Resolve-TargetPath([string]$inputPath) {
    if ([string]::IsNullOrWhiteSpace($inputPath)) {
        Throw-SpecLintError "Spec lint directory is empty."
    }

    $candidate = if ([System.IO.Path]::IsPathRooted($inputPath)) { $inputPath } else { Join-Path $Root $inputPath }
    if (-not (Test-Path -LiteralPath $candidate)) {
        Throw-SpecLintError "Spec lint directory not found: $inputPath"
    }

    return (Resolve-Path -LiteralPath $candidate).Path
}

function Read-Text([string]$path) {
    if (-not (Test-Path -LiteralPath $path)) { return $null }
    return Get-Content -LiteralPath $path -Raw
}

function Parse-Field([string]$text, [string]$pattern) {
    if (-not $text) { return $null }
    $match = [regex]::Match($text, $pattern, [System.Text.RegularExpressions.RegexOptions]::Multiline)
    if ($match.Success) { return $match.Groups[1].Value.Trim() }
    return $null
}

function New-Package([string]$path) {
    $bucket = "_template"
    if ($path -match '[\\/]_active[\\/]') { $bucket = "_active" }
    elseif ($path -match '[\\/]_done[\\/]') { $bucket = "_done" }
    [PSCustomObject]@{
        Path = $path
        Bucket = $bucket
    }
}

function New-Issue {
    param(
        [string]$Package,
        [string]$Code,
        [string]$Message,
        [string]$Fix
    )

    [PSCustomObject]@{
        Package = $Package
        Code = $Code
        Message = $Message
        Fix = $Fix
    }
}

function Get-Packages([string]$targetPath) {
    $packages = New-Object System.Collections.Generic.List[object]

    $item = Get-Item -LiteralPath $targetPath
    if (-not $item.PSIsContainer) {
        Throw-SpecLintError "Spec lint target must be a directory: $targetPath"
    }

    $specPath = Join-Path $targetPath "spec.yaml"
    if (Test-Path -LiteralPath $specPath) {
        $packages.Add((New-Package $targetPath))
        return $packages
    }

    Get-ChildItem -LiteralPath $targetPath -Directory -Recurse | ForEach-Object {
        $childSpec = Join-Path $_.FullName "spec.yaml"
        if (Test-Path -LiteralPath $childSpec) {
            $packages.Add((New-Package $_.FullName))
        }
    }

    return $packages
}

function Get-ExpectedDocsRefs([string]$packagePath, [string]$bucket) {
    $folderName = Split-Path $packagePath -Leaf
    $expected = New-Object System.Collections.Generic.List[string]

    foreach ($file in $RequiredFiles) {
        if ($file -eq "spec.yaml") { continue }

        if ($bucket -eq "_template") {
            $expected.Add($file)
        } else {
            $expected.Add("docs/specs/$bucket/$folderName/$file")
        }
    }

    return $expected
}

function Write-IssueReport([System.Collections.Generic.List[object]]$issues) {
    $packageCount = ($issues | Select-Object -ExpandProperty Package -Unique).Count
    Write-Host "spec-lint: fail ($($issues.Count) issue(s) in $packageCount package(s))"

    foreach ($group in ($issues | Group-Object Package | Sort-Object Name)) {
        Write-Host ""
        Write-Host "Package: $($group.Name)"
        foreach ($issue in ($group.Group | Sort-Object Code, Message)) {
            Write-Host "  - [$($issue.Code)] $($issue.Message)"
            if ($issue.Fix) {
                Write-Host "    Fix: $($issue.Fix)"
            }
        }
    }
}

$resolvedTarget = Resolve-TargetPath $Directory
Assert-ReadOnlyScript
$packages = Get-Packages $resolvedTarget
if ($packages.Count -eq 0) {
    Throw-SpecLintError "No spec packages found under: $resolvedTarget"
}

$issues = New-Object System.Collections.Generic.List[object]

foreach ($pkg in $packages) {
    $readmePath = Join-Path $pkg.Path "README.md"
    $specPath = Join-Path $pkg.Path "spec.yaml"
    $notesPath = Join-Path $pkg.Path "implementation-notes.md"
    $folderName = Split-Path $pkg.Path -Leaf

    $missing = New-Object System.Collections.Generic.List[string]
    foreach ($file in $RequiredFiles) {
        $filePath = Join-Path $pkg.Path $file
        if (-not (Test-Path -LiteralPath $filePath)) {
            $missing.Add($filePath)
        }
    }
    foreach ($path in $missing) {
        $issues.Add((New-Issue $pkg.Path "MISSING_FILE" "Missing required file: $path" "Create the missing file before re-running spec-lint."))
    }
    if ($missing.Count -gt 0) {
        continue
    }

    $readme = Read-Text $readmePath
    $spec = Read-Text $specPath
    if (-not $readme -or -not $spec) {
        $issues.Add((New-Issue $pkg.Path "UNREADABLE_PACKAGE" "Unreadable spec package: $($pkg.Path)" "Fix the missing or unreadable file, then re-run spec-lint."))
        continue
    }

    $readmeStatus = Parse-Field $readme '^Status:\s*`([^`]+)`\s*$'
    $specStatus = Parse-Field $spec '^status:\s*([A-Za-z]+)\s*$'
    $specId = Parse-Field $spec '^id:\s*([^\s]+)\s*$'
    $specImplementer = Parse-Field $spec '^implementer:\s*([^\s]+)\s*$'
    $notes = Read-Text $notesPath

    if (-not $readmeStatus) {
        $issues.Add((New-Issue $pkg.Path "README_STATUS_MISSING" "Missing README status in $($pkg.Path)" "Add a line like `Status: `draft`` or `Status: `done`` near the top of README.md."))
    }

    if (-not $specStatus) {
        $issues.Add((New-Issue $pkg.Path "SPEC_STATUS_MISSING" "Missing spec.yaml status in $($pkg.Path)" "Add a top-level `status:` field in spec.yaml."))
    }

    if ($readmeStatus -and $specStatus -and $readmeStatus -ne $specStatus) {
        $issues.Add((New-Issue $pkg.Path "STATUS_MISMATCH" "Status mismatch in $($pkg.Path): README=$readmeStatus spec.yaml=$specStatus" "Make both status values match before re-running spec-lint."))
    }

    switch ($pkg.Bucket) {
        "_template" {
            if ($specStatus -and $specStatus -ne "draft") {
                $issues.Add((New-Issue $pkg.Path "TEMPLATE_STATUS_INVALID" "Template must stay draft: $($pkg.Path) has status=$specStatus" "Set both README and spec.yaml status to draft."))
            }

            if ($specImplementer -and $specImplementer -ne "pending") {
                $issues.Add((New-Issue $pkg.Path "TEMPLATE_IMPLEMENTER_INVALID" "Template implementer must stay pending: $($pkg.Path) has implementer=$specImplementer" "Reset implementer to pending in spec.yaml."))
            }

            if ($specId -and $specId -ne "<initiative-id>") {
                $issues.Add((New-Issue $pkg.Path "TEMPLATE_ID_INVALID" "Template spec.yaml id should stay as <initiative-id>: found id=$specId" "Reset the template id placeholder before using it as a starter."))
            }

            foreach ($file in $RequiredFiles) {
                if ($file -eq "spec.yaml") { continue }
                if ($spec -notmatch [regex]::Escape($file)) {
                    $issues.Add((New-Issue $pkg.Path "TEMPLATE_DOC_REF_MISSING" "Missing required template reference in spec.yaml: $file" "Keep the template docs list aligned with the starter files."))
                }
            }
        }
        "_active" {
            if ($specStatus -and $specStatus -notin @("approved", "implementing")) {
                $issues.Add((New-Issue $pkg.Path "ACTIVE_STATUS_INVALID" "Active spec must be approved or implementing: $($pkg.Path) has status=$specStatus" "Set both README and spec.yaml status to approved or implementing."))
            }

            foreach ($expectedRef in (Get-ExpectedDocsRefs $pkg.Path $pkg.Bucket)) {
                if ($spec -notmatch [regex]::Escape($expectedRef)) {
                    $issues.Add((New-Issue $pkg.Path "DOC_REF_MISSING" "Missing required spec.yaml reference: $expectedRef" "Update the docs list in spec.yaml to point at the current package path."))
                }
            }

            $staleDonePrefix = "docs/specs/_done/$folderName/"
            if ($spec -match [regex]::Escape($staleDonePrefix)) {
                $issues.Add((New-Issue $pkg.Path "DOC_REF_STALE" "spec.yaml still references done-path docs for an active package: $staleDonePrefix" "Rewrite every docs/specs/_done/$folderName/... entry to docs/specs/_active/$folderName/...."))
            }
        }
        "_done" {
            if ($specStatus -and $specStatus -ne "done") {
                $issues.Add((New-Issue $pkg.Path "DONE_STATUS_INVALID" "Done spec must be done: $($pkg.Path) has status=$specStatus" "Set both README and spec.yaml status to done before archiving."))
            }

            if (-not $notes -or $notes.Trim().Length -eq 0) {
                $issues.Add((New-Issue $pkg.Path "DONE_NOTES_EMPTY" "Done spec must have implementation notes: $($pkg.Path)" "Add a short implementation summary to implementation-notes.md before archiving."))
            }

            if ($specImplementer -eq "pending") {
                $issues.Add((New-Issue $pkg.Path "DONE_IMPLEMENTER_PENDING" "Done spec must not have a pending implementer: $($pkg.Path)" "Set implementer to implementation-agent or another archived value before moving it to _done/."))
            }

            foreach ($expectedRef in (Get-ExpectedDocsRefs $pkg.Path $pkg.Bucket)) {
                if ($spec -notmatch [regex]::Escape($expectedRef)) {
                    $issues.Add((New-Issue $pkg.Path "DOC_REF_MISSING" "Missing required spec.yaml reference: $expectedRef" "Update the docs list in spec.yaml to point at the current package path."))
                }
            }

            $staleActivePrefix = "docs/specs/_active/$folderName/"
            if ($spec -match [regex]::Escape($staleActivePrefix)) {
                $issues.Add((New-Issue $pkg.Path "DOC_REF_STALE" "spec.yaml still references active-path docs for a done package: $staleActivePrefix" "Rewrite every docs/specs/_active/$folderName/... entry to docs/specs/_done/$folderName/...."))
            }
        }
        default {
            $issues.Add((New-Issue $pkg.Path "UNKNOWN_BUCKET" "Unknown spec bucket for $($pkg.Path): $($pkg.Bucket)" "Move the package under docs/specs/_template, docs/specs/_active, or docs/specs/_done."))
        }
    }

    if ($pkg.Bucket -ne "_template" -and $specId -and $specId -ne $folderName) {
        $issues.Add((New-Issue $pkg.Path "ID_FOLDER_MISMATCH" "Folder/id mismatch in $($pkg.Path): folder=$folderName spec.yaml id=$specId" "Rename the folder or update spec.yaml id so they match."))
    }
}

if ($issues.Count -gt 0) {
    Write-IssueReport $issues
    exit 1
}

Write-Host "spec-lint: pass ($($packages.Count) package(s))"
