#!/usr/bin/env pwsh
# System-owned spec workspace lint. Do not edit this file unless the task is explicitly about the spec system.
[CmdletBinding()]
param(
    [Parameter(Mandatory = $false)]
    [string]$Directory
)

$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $MyInvocation.MyCommand.Path

$requiredFiles = @(
    "README.md",
    "spec.yaml",
    "baseline.md",
    "internal-api-outline.md",
    "plan.md",
    "validation-checklist.md",
    "ci-commands.md",
    "decisions.md",
    "quality-rules.md",
    "implementation-notes.md"
)

function Throw-SpecLintError([string]$message) {
    throw $message
}

function Read-Text([string]$path) {
    if (-not (Test-Path -LiteralPath $path)) { return $null }
    return Get-Content -LiteralPath $path -Raw
}

function Parse-Field([string]$text, [string]$pattern) {
    if (-not $text) { return $null }
    $match = [regex]::Match($text, $pattern, [System.Text.RegularExpressions.RegexOptions]::Multiline)
    if ($match.Success) { return $match.Groups[1].Value.Trim() }
    return $null
}

function New-Package([string]$path, [string]$bucket) {
    [PSCustomObject]@{
        Path = $path
        Bucket = $bucket
    }
}

function Add-Issue {
    param(
        [System.Collections.Generic.List[object]]$List,
        [string]$PackagePath,
        [string]$Code,
        [string]$Message,
        [string]$Fix = ""
    )

    $List.Add([PSCustomObject]@{
        Package = $PackagePath
        Code = $Code
        Message = $Message
        Fix = $Fix
    })
}

function Get-WorkspacePackages {
    $packages = New-Object System.Collections.Generic.List[object]

    $templatePath = Join-Path $root "docs\specs\_template"
    if (-not (Test-Path -LiteralPath $templatePath)) {
        Throw-SpecLintError "Missing spec template: $templatePath"
    }
    $packages.Add((New-Package $templatePath "_template"))

    foreach ($bucket in @("_active", "_done")) {
        $bucketPath = Join-Path $root "docs\specs\$bucket"
        if (-not (Test-Path -LiteralPath $bucketPath)) {
            Throw-SpecLintError "Missing spec bucket: $bucketPath"
        }

        Get-ChildItem -LiteralPath $bucketPath -Directory | ForEach-Object {
            $packages.Add((New-Package $_.FullName $bucket))
        }
    }

    return $packages
}

function Get-TargetPackages([string]$directory) {
    if ([string]::IsNullOrWhiteSpace($directory)) {
        return Get-WorkspacePackages
    }

    $candidate = if ([System.IO.Path]::IsPathRooted($directory)) { $directory } else { Join-Path $root $directory }
    if (-not (Test-Path -LiteralPath $candidate)) {
        Throw-SpecLintError "Spec lint directory not found: $Directory"
    }

    $resolved = (Resolve-Path -LiteralPath $candidate).Path
    $packages = New-Object System.Collections.Generic.List[object]

    if (Test-Path -LiteralPath (Join-Path $resolved "spec.yaml")) {
        $bucket = "_template"
        if ($resolved -match '[\\/]_active[\\/]') { $bucket = "_active" }
        elseif ($resolved -match '[\\/]_done[\\/]') { $bucket = "_done" }
        $packages.Add((New-Package $resolved $bucket))
        return $packages
    }

    Get-ChildItem -LiteralPath $resolved -Directory -Recurse | ForEach-Object {
        if (Test-Path -LiteralPath (Join-Path $_.FullName "spec.yaml")) {
            $bucket = "_template"
            if ($_.FullName -match '[\\/]_active[\\/]') { $bucket = "_active" }
            elseif ($_.FullName -match '[\\/]_done[\\/]') { $bucket = "_done" }
            $packages.Add((New-Package $_.FullName $bucket))
        }
    }

    if ($packages.Count -eq 0) {
        Throw-SpecLintError "No spec packages found under: $resolved"
    }

    return $packages
}

function Get-RelativePackagePath([object]$pkg) {
    if ($pkg.Bucket -eq "_template") {
        return "docs/specs/_template"
    }

    $folderName = Split-Path $pkg.Path -Leaf
    return "docs/specs/$($pkg.Bucket)/$folderName"
}

function Write-IssueReport([System.Collections.Generic.List[object]]$issues) {
    $uniquePackages = $issues | Select-Object -ExpandProperty Package -Unique
    Write-Host "spec-lint: fail ($($issues.Count) issue(s) in $($uniquePackages.Count) package(s))"

    foreach ($group in ($issues | Group-Object Package | Sort-Object Name)) {
        Write-Host ""
        Write-Host "Package: $($group.Name)"
        foreach ($issue in ($group.Group | Sort-Object Code, Message)) {
            Write-Host "  - [$($issue.Code)] $($issue.Message)"
            if ($issue.Fix) {
                Write-Host "    Fix: $($issue.Fix)"
            }
        }
    }
}

$packages = Get-TargetPackages $Directory
$issues = New-Object System.Collections.Generic.List[object]
$packageCount = 0

foreach ($pkg in $packages) {
    $packageCount++
    $folderName = Split-Path $pkg.Path -Leaf
    $readmePath = Join-Path $pkg.Path "README.md"
    $specPath = Join-Path $pkg.Path "spec.yaml"
    $notesPath = Join-Path $pkg.Path "implementation-notes.md"
    $relativePackagePath = Get-RelativePackagePath $pkg

    $missingRequiredFileCount = 0
    foreach ($file in $requiredFiles) {
        $filePath = Join-Path $pkg.Path $file
        if (-not (Test-Path -LiteralPath $filePath)) {
            Add-Issue -List $issues -PackagePath $pkg.Path -Code "MISSING_FILE" -Message "Missing required file: $filePath" -Fix "Create the missing file before re-running spec-lint."
            $missingRequiredFileCount++
        }
    }

    if ($missingRequiredFileCount -gt 0) {
        continue
    }

    $readme = Read-Text $readmePath
    $spec = Read-Text $specPath
    if (-not $readme -or -not $spec) {
        Add-Issue -List $issues -PackagePath $pkg.Path -Code "UNREADABLE_PACKAGE" -Message "Unreadable spec package: $($pkg.Path)" -Fix "Fix the missing or unreadable file, then re-run spec-lint."
        continue
    }

    $readmeStatus = Parse-Field $readme '^Status:\s*`([^`]+)`\s*$'
    $specStatus = Parse-Field $spec '^status:\s*([A-Za-z]+)\s*$'
    $specId = Parse-Field $spec '^id:\s*([^\s]+)\s*$'
    $specImplementer = Parse-Field $spec '^implementer:\s*([^\s]+)\s*$'
    $notes = Read-Text $notesPath

    if (-not $readmeStatus) {
        Add-Issue -List $issues -PackagePath $pkg.Path -Code "README_STATUS_MISSING" -Message "Missing README status in $($pkg.Path)" -Fix "Add a line like `Status: `draft`` or `Status: `done`` near the top of README.md."
    }

    if (-not $specStatus) {
        Add-Issue -List $issues -PackagePath $pkg.Path -Code "SPEC_STATUS_MISSING" -Message "Missing spec.yaml status in $($pkg.Path)" -Fix "Add a top-level `status:` field in spec.yaml."
    }

    if ($readmeStatus -and $specStatus -and $readmeStatus -ne $specStatus) {
        Add-Issue -List $issues -PackagePath $pkg.Path -Code "STATUS_MISMATCH" -Message "Status mismatch in $($pkg.Path): README=$readmeStatus spec.yaml=$specStatus" -Fix "Make both status values match before re-running spec-lint."
    }

    if ($pkg.Bucket -eq "_template") {
        foreach ($file in $requiredFiles) {
            if ($file -eq "spec.yaml") { continue }
            if ($spec -notmatch [regex]::Escape($file)) {
                Add-Issue -List $issues -PackagePath $pkg.Path -Code "TEMPLATE_DOC_REF_MISSING" -Message "Missing required template reference in spec.yaml: $file" -Fix "Keep the template docs list aligned with the starter files."
            }
        }
    }
    else {
        foreach ($file in $requiredFiles) {
            if ($file -eq "spec.yaml") { continue }
            $expectedRef = "$relativePackagePath/$file"
            if ($spec -notmatch [regex]::Escape($expectedRef)) {
                Add-Issue -List $issues -PackagePath $pkg.Path -Code "DOC_REF_MISSING" -Message "Missing required spec.yaml reference: $expectedRef" -Fix "Update the docs list in spec.yaml to point at the current package path."
            }
        }
    }

    if ($pkg.Bucket -eq "_done") {
        $staleActivePrefix = "docs/specs/_active/$folderName/"
        if ($spec -match [regex]::Escape($staleActivePrefix)) {
            Add-Issue -List $issues -PackagePath $pkg.Path -Code "DOC_REF_STALE" -Message "spec.yaml still references active-path docs for a done package: $staleActivePrefix" -Fix "Rewrite every docs/specs/_active/$folderName/... entry to docs/specs/_done/$folderName/...."
        }
    }

    if ($pkg.Bucket -eq "_active") {
        $staleDonePrefix = "docs/specs/_done/$folderName/"
        if ($spec -match [regex]::Escape($staleDonePrefix)) {
            Add-Issue -List $issues -PackagePath $pkg.Path -Code "DOC_REF_STALE" -Message "spec.yaml still references done-path docs for an active package: $staleDonePrefix" -Fix "Rewrite every docs/specs/_done/$folderName/... entry to docs/specs/_active/$folderName/...."
        }
    }

    switch ($pkg.Bucket) {
        "_template" {
            if ($specStatus -and $specStatus -ne "draft") {
                Add-Issue -List $issues -PackagePath $pkg.Path -Code "TEMPLATE_STATUS_INVALID" -Message "Template must stay draft: $($pkg.Path) has status=$specStatus" -Fix "Set both README and spec.yaml status to draft."
            }

            if ($specImplementer -and $specImplementer -ne "pending") {
                Add-Issue -List $issues -PackagePath $pkg.Path -Code "TEMPLATE_IMPLEMENTER_INVALID" -Message "Template implementer must stay pending: $($pkg.Path) has implementer=$specImplementer" -Fix "Reset implementer to pending in spec.yaml."
            }

            if ($specId -and $specId -ne "<initiative-id>") {
                Add-Issue -List $issues -PackagePath $pkg.Path -Code "TEMPLATE_ID_INVALID" -Message "Template spec.yaml id should stay as <initiative-id>: found id=$specId" -Fix "Reset the template id placeholder before using it as a starter."
            }
        }
        "_active" {
            if ($specStatus -and $specStatus -notin @("approved", "implementing")) {
                Add-Issue -List $issues -PackagePath $pkg.Path -Code "ACTIVE_STATUS_INVALID" -Message "Active spec must be approved or implementing: $($pkg.Path) has status=$specStatus" -Fix "Set both README and spec.yaml status to approved or implementing."
            }
        }
        "_done" {
            if ($specStatus -and $specStatus -ne "done") {
                Add-Issue -List $issues -PackagePath $pkg.Path -Code "DONE_STATUS_INVALID" -Message "Done spec must be done: $($pkg.Path) has status=$specStatus" -Fix "Set both README and spec.yaml status to done before archiving."
            }

            if (-not $notes -or $notes.Trim().Length -eq 0) {
                Add-Issue -List $issues -PackagePath $pkg.Path -Code "DONE_NOTES_EMPTY" -Message "Done spec must have implementation notes: $($pkg.Path)" -Fix "Add a short implementation summary to implementation-notes.md before archiving."
            }

            if ($specImplementer -eq "pending") {
                Add-Issue -List $issues -PackagePath $pkg.Path -Code "DONE_IMPLEMENTER_PENDING" -Message "Done spec must not have a pending implementer: $($pkg.Path)" -Fix "Set implementer to implementation-agent or another archived value before moving it to _done/."
            }
        }
    }

    if ($pkg.Bucket -ne "_template" -and $specId -and $specId -ne $folderName) {
        Add-Issue -List $issues -PackagePath $pkg.Path -Code "ID_FOLDER_MISMATCH" -Message "Folder/id mismatch in $($pkg.Path): folder=$folderName spec.yaml id=$specId" -Fix "Rename the folder or update spec.yaml id so they match."
    }
}

if ($issues.Count -gt 0) {
    Write-IssueReport $issues
    exit 1
}

Write-Host "spec-lint: pass ($packageCount package(s))"
