# Build Performance Benchmark Config

[build]
jobs = 32
# rustc-wrapper = "sccache"

[target.x86_64-pc-windows-msvc]
# linker = "lld-link.exe"

[profile.dev]
debug = "line-tables-only"
opt-level = 1
lto = "off"
codegen-units = 32
incremental = true

[profile.dev.build-override]
opt-level = 3
codegen-units = 16

[profile.release]
lto = "thin"
codegen-units = 32
debug = "line-tables-only"
opt-level = 3

[profile.release.build-override]
opt-level = 3
codegen-units = 16

[profile.fast-release]
inherits = "release"
lto = "off"
codegen-units = 128
opt-level = 2
