@echo off
setlocal enabledelayedexpansion

set "ROOT=%~dp0"
pushd "%ROOT%"

:: ============================================================================
:: Auto-Rust Windows Setup Script
:: - Detects CPU threads and optimizes build configuration
:: - Installs LLVM (lld-link) for faster linking
:: - Creates .env file with template settings
:: - Builds release version
:: ============================================================================

echo ========================================
echo Auto-Rust Windows Setup
echo ========================================
echo.

:: ----------------------------------------------------------------------------
:: Step 1: Install Build Dependencies (LLVM)
:: ----------------------------------------------------------------------------
echo [1/7] Installing build accelerator (LLVM)...

where lld-link >nul 2>&1
if %ERRORLEVEL% neq 0 (
    echo   lld-link not found. Installing LLVM...
    choco install llvm -y
    setx PATH "%PATH%;C:\Program Files\LLVM\bin" >nul 2>&1
    echo   Added LLVM to PATH
) else (
    echo   lld-link found: OK
)

refreshenv >nul 2>&1
echo.

:: ----------------------------------------------------------------------------
:: Step 2: CPU Detection and Optimization
:: ----------------------------------------------------------------------------
echo [2/7] Detecting CPU threads...

for /f "tokens=2" %%a in ('wmic cpu get NumberOfLogicalProcessors /value ^| find "NumberOfLogicalProcessors"') do (
    set /a THREADS=%%a
)
if not defined THREADS set THREADS=4

set /a JOBS=THREADS-1
if !JOBS! lss 1 set JOBS=1

echo   Detected CPU threads: %THREADS%
echo   Setting build jobs to: %JOBS%
echo.

if not exist ".cargo" mkdir .cargo

echo [3/7] Configuring Cargo for optimal builds...
(
    echo # Cargo configuration for faster builds with automatic CPU detection
    echo # Generated by setup-windows.bat on %DATE% %TIME%
    echo.
    echo [build]
    echo jobs = %JOBS%
    echo.
    echo # sccache intentionally not configured in this repository.
    echo # Keep builds on plain Cargo incremental compilation for reliability.
    echo.
    echo [target.x86_64-pc-windows-msvc]
    echo linker = "C:\\Program Files\\LLVM\\bin\\lld-link.exe"
    echo.
    echo [profile.dev]
    echo debug = "none"
    echo opt-level = 0
    echo lto = "off"
    echo codegen-units = 16
    echo incremental = true
    echo overflow-checks = false
    echo.
    echo [profile.dev.package."*"]
    echo debug = false
    echo opt-level = 0
    echo.
    echo [profile.dev.build-override]
    echo opt-level = 3
    echo codegen-units = 16
    echo.
    echo [profile.release]
    echo lto = "thin"
    echo codegen-units = 1
    echo debug = false
    echo opt-level = 3
    echo strip = "debuginfo"
    echo panic = "unwind"
    echo overflow-checks = false
    echo.
    echo [profile.release.build-override]
    echo opt-level = 3
    echo codegen-units = 16
    echo.
    echo [profile.fast-release]
    echo inherits = "release"
    echo lto = "off"
    echo codegen-units = 64
    echo opt-level = 2
) > .cargo\config.toml

echo   Created .cargo/config.toml with %JOBS% parallel jobs and lld-link
echo.

:: ----------------------------------------------------------------------------
:: Step 4: Check Rust Installation
:: ----------------------------------------------------------------------------
echo [4/7] Checking Rust installation...

rustc --version >nul 2>&1
if errorlevel 1 (
    echo   Rust not found. Install rustup manually, then re-run this script.
    exit /b 1
) else (
    rustc --version
    echo   Rust is already installed
)
echo.

:: ----------------------------------------------------------------------------
:: Step 5: Install auto launcher on PATH
:: ----------------------------------------------------------------------------
echo [5/7] Installing auto launcher on PATH...

set "AUTO_LAUNCHER_DIR=%ROOT%config"
if not exist "%AUTO_LAUNCHER_DIR%\auto.cmd" (
    echo   auto launcher not found at %AUTO_LAUNCHER_DIR%\auto.cmd
    echo   Please create config\auto.cmd first.
    exit /b 1
)

powershell -NoProfile -ExecutionPolicy Bypass -Command "$root = (Resolve-Path '%AUTO_LAUNCHER_DIR%').Path; $path = [Environment]::GetEnvironmentVariable('Path','User'); $parts = @(); if ($path) { $parts = $path -split ';' ^| Where-Object { $_ -and (-not (Test-Path (Join-Path $_ 'auto.cmd')) -and -not (Test-Path (Join-Path $_ 'auto.bat')) -and -not (Test-Path (Join-Path $_ 'auto.exe'))) } }; $newPath = @($root) + $parts ^| Select-Object -Unique; [Environment]::SetEnvironmentVariable('Path', ($newPath -join ';'), 'User'); Write-Host ('Rebuilt PATH and moved ' + $root + ' to front')"
if errorlevel 1 (
    echo   Failed to update user PATH.
    exit /b 1
)
echo.

:: ----------------------------------------------------------------------------
:: Step 6: Create .env File
:: ----------------------------------------------------------------------------
echo [6/7] Creating .env file...

if exist ".env" (
    echo   .env file already exists, skipping...
) else (
    (
        echo # Auto-Rust Environment Configuration
        echo # Generated by setup-windows.bat
        echo.
        echo LLM_PROVIDER=ollama
        echo OPENROUTER_API_KEY=
        echo OPENROUTER_MODEL=anthropic/claude-3-haiku
        echo OLLAMA_URL=http://localhost:11434
        echo OLLAMA_MODEL=llama3.2:3b
        echo.
        echo TWITTER_LLM_ENABLED=false
        echo TWITTER_LLM_PROVIDER=ollama
        echo TWITTER_LLM_MODEL=llama3.2:3b
        echo TWITTER_LLM_REPLY_PROBABILITY=0.05
        echo TWITTER_LLM_QUOTE_PROBABILITY=0.15
        echo.
        echo TWITTER_MAX_LIKES=5
        echo TWITTER_MAX_RETWEETS=3
        echo TWITTER_MAX_FOLLOWS=2
        echo TWITTER_MAX_REPLIES=3
        echo TWITTER_MAX_THREAD_DIVES=3
        echo TWITTER_MAX_TOTAL_ACTIONS=10
        echo.
        echo ROXYBROWSER_API_URL=http://127.0.0.1:50000/
        echo ROXYBROWSER_API_KEY=
        echo CURSOR_OVERLAY_MS=50
        echo.
        echo MAX_GLOBAL_CONCURRENCY=20
        echo TASK_TIMEOUT_MS=600000
        echo MAX_RETRIES=2
    ) > .env
    echo   Created .env file with template settings
)
echo.

:: ----------------------------------------------------------------------------
:: Step 7: Build Project
:: ----------------------------------------------------------------------------
echo [7/7] Building project...
echo.

call cargo clean
call cargo build --profile release --all-features
if errorlevel 1 (
    echo.
    echo ========================================
    echo Build failed! Check errors above.
    echo ========================================
    exit /b 1
)

echo.
echo ========================================
echo Setup Complete!
echo ========================================
echo.
echo Configuration:
echo   CPU threads detected: %THREADS%
echo   Build jobs: %JOBS%
echo   lld-link: ENABLED
echo   Build profile: release ^(optimized with thin LTO^)
echo.
echo Build Tips:
echo   - Keep incremental builds enabled for fast edit/compile cycles
echo   - Use lld-link for faster Windows linking
echo.
echo Next steps:
echo   1. Add your API keys to .env file
echo   2. Run: auto task1 task2 then task3
echo.

popd
pause
